### ISSUE TITLE
unable to add activities from the subpanel, only shows the heading.

### ISSUE THREAD

**Issue by GeorgeWL** [blasher/tabbed_subpanels#1]
![image](https://cloud.githubusercontent.com/assets/5931248/18669938/47fe398e-7f35-11e6-86df-bc07922c2f0c.png)

I have yet to see other issues however

![image](https://cloud.githubusercontent.com/assets/5931248/18669951/585d95ea-7f35-11e6-80e3-a2d3262b40fe.png)

**Comment by blasher** [comment]
George, this is VERY LIKELY a result of a race condition that currently exists in the code that i have been battling since i first wrote it.  i will continue to try to fix this soon.

**Comment by GeorgeWL** [comment]
@blasher alright, I'd help if I knew how.

**Comment by blasher** [comment]
@GeorgeWL , curious what browser you are using.  also, if you know how to get into the javascript console in the developer tools on chrome, if you could send me a copy and paste of its contents that may help.

**Comment by blasher** [comment]
@GeorgeWL , what i am interested in is seeing the progression of the page load / script actions.  it should look a little something like this...
![mwsnap028 2016-09-30 10_00_48](https://cloud.githubusercontent.com/assets/5833506/18996163/e6d5e086-86f4-11e6-9521-c9558fdce3f0.jpg)

**Comment by GeorgeWL** [comment]
Yeah I know how to get into console,  and my browser is Chrome. 

I'll look when I'm next in work

**Comment by blasher** [comment]
Cool.  Thanks George. 

-Brian

**Comment by blasher** [comment]
so, i finally got my requirements for a project i am currently working on and can revisit this.  actually found a case in my own system where i can reproduce the race condition fail and think i have a plan on how to fix it (had already implemented some of the code, but not all of it).

**Comment by blasher** [comment]
george.  i've modified the code to help battle the race condition issue.  try it again.  the only file that changed was the JS file.  lmk.

**Comment by GeorgeWL** [comment]
I'm about to try reinstalling it now, will let you know.

sorry for only just coming back to it.

**Comment by GeorgeWL** [comment]
Works perfectly, great job on the fix. 👍
