### ISSUE TITLE
Disable has no effect, has to be uninstalled

### ISSUE THREAD

**Issue by GeorgeWL** [blasher/tabbed_subpanels#2]
Just to test things, I disabled the module as it was conflicting through no fault of your own.

Upon disabling however, the module still was having effect, and wouldn't stop affecting until it was uninstalled.

**Comment by blasher** [comment]
i'm not quite sure that I understand.   do you mean that the subpanels were still tabbed even after disabling the module in module loade?

**Comment by GeorgeWL** [comment]
@blasher  precisely that yeah.

**Comment by blasher** [comment]
this sounds like a CRM caching issue and not necessarily an issue with the plugin.  i know i hate when people ask me this, but i have to ask, "did you run a repair and rebuild after you disabled"?  as for the race condition issue i am aware of it, and like i said, will try to provide a better solution as soon as possible.  and thanks for the feedback! :)
